### ISSUE TITLE
Cannot enable integration on Home Assistant OS

### ISSUE THREAD

**Issue by bengeek2** [npope/home-assistant-crestron-component#14]
I have added the entry
"crestron:
  port: 45000"
and all other entries for switches/sensors to my configuration.yaml. I have not received any errors, and I fully rebooted the OS. All entities have appeared but they are listed as unavailable. I cannot see the Crestron integration in my current list. If I click "add integration", it is in the available to add list, but clicking the add button responds with
"This device cannot be added from the UI
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."

My configuration.yaml is:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  packages: !include_dir_named packages/
crestron:
  port: 45000"
switch:
  - platform: crestron
    name: "Audio Toggle"
    switch_join: 3
binary_sensor:
  - platform: crestron
    name: "Audio Pwr Progress"
    is_on_join: 2
    device_class: running
binary_sensor:
  - platform: crestron
    name: "Audio Turning Off"
    is_on_join: 4
    device_class: running
binary_sensor:
  - platform: crestron
    name: "Audio Turning On"
    is_on_join: 3
    device_class: running
binary_sensor:
  - platform: crestron
    name: "Audio State"
    is_on_join: 5
    device_class: power

```
