### ISSUE TITLE
How to take an analog join into a number?

### ISSUE THREAD

**Issue by Bagunda** [npope/home-assistant-crestron-component#5]
Please show an example - how to take an analog join into a number in Home Assistant.

**Comment by Bagunda** [comment]
I found the answer. Thanx.

In configuration.yaml:
```
input_number:
  slider1:
    name: Slider
    initial: 0
    min: 0
    max: 65535
    step: 1
  box1:
    name: Numeric Input Box
    initial: 0
    min: 0
    max: 65535
    step: 1
    mode: box

crestron:
  port: 16384
  from_joins:
    - join: a1
      script:
        service: input_number.set_value
        data:
          entity_id: input_number.slider1
          value: "{{value|int}}"
    - join: a2
      script:
        service: input_number.set_value
        data:
          entity_id: input_number.box1
          value: "{{value|int}}"
```
In SIMPL Windows:
![2022-02-28_18-19-28](https://user-images.githubusercontent.com/16766521/156008688-cd462da3-e53f-4136-9e69-9497fd67fa64.png)

**Comment by LancerJun** [comment]
Why can't my control system connect to ha

**Comment by Bagunda** [comment]
> 
Copy all files from this repo to /config/custom_components/crestron
![image](https://user-images.githubusercontent.com/16766521/194891022-efe2fdec-6241-493b-83d7-6af60836256c.png)

In configuration.yaml:
```
input_number:
  slider1:
    name: Slider
    initial: 0
    min: 0
    max: 65535
    step: 1
  box1:
    name: Numeric Input Box
    initial: 0
    min: 0
    max: 65535
    step: 1
    mode: box

crestron:
  port: 16384
  from_joins:
    - join: a1
      script:
        service: input_number.set_value
        data:
          entity_id: input_number.slider1
          value: "{{value|int}}"
    - join: a2
      script:
        service: input_number.set_value
        data:
          entity_id: input_number.box1
          value: "{{value|int}}"
```

Then Reboot Home Assistant.

In Crestron see my pic above.
In Crestron TCP/IP_Client dont forget IP addres to Home Assistant (becouse HA - is TCP/IP server), and port.
